name: CI/CD Backend
on:
  push:
    branches: [ "deploy" ]

jobs:
  deploy-to-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Desplegar en EC2 Backend mediante Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_BACKEND_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Clona o actualiza el repo directamente en la EC2 (Asegúrate de que la EC2 tenga acceso a git o usa el método de copia)
            cd ~/devops-evaluacion-2-backend || git clone -b deploy https://github.com/TU_USUARIO/devops-evaluacion-2-backend.git ~/devops-evaluacion-2-backend
            cd ~/devops-evaluacion-2-backend
            git pull origin deploy
            sudo docker compose up -d --build
