name: CI/CD Backend
on:
  push:
    branches: [ "deploy" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push API Ventas
        uses: docker/build-push-action@v5
        with:
          context: ./back-Ventas_SpringBoot/Springboot-API-REST
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/api-ventas:latest

      - name: Build and Push API Despachos
        uses: docker/build-push-action@v5
        with:
          context: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/api-despachos:latest

  deploy-to-ec2:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Desplegar en EC2 Backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_BACKEND_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. Limpiamos y clonamos el repositorio
            rm -rf ~/devops-evaluacion-2-backend
            git clone -b deploy https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git ~/devops-evaluacion-2-backend
            cd ~/devops-evaluacion-2-backend
            
            # 2. Descargamos las imágenes nuevas desde Docker Hub y levantamos
            sudo docker-compose pull
            sudo docker-compose down || true
            sudo docker-compose up -d
