name: CI/CD Backend
on:
  push:
    branches: [ "deploy" ]

jobs:
  deploy-to-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Desplegar en EC2 Backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_BACKEND_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. Borramos la carpeta antigua para que no haya conflictos
            rm -rf ~/devops-evaluacion-2-backend
            
            # 2. Clonamos con la variable magica de GitHub (no necesitas configurar este secreto, viene por defecto)
            git clone -b deploy https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git ~/devops-evaluacion-2-backend
            
            # 3. Entramos a la carpeta
            cd ~/devops-evaluacion-2-backend
            
            # 4. Levantamos los contenedores usando docker-compose CON GUION
            sudo docker-compose down || true
            sudo docker-compose up -d --build
